# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='documento',
            field=models.ImageField(null=True, upload_to='documentos/'),
        ),
    ]
