# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='curp',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
