# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0002_auto_20181230_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='documento',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
    ]
