# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0002_auto_20181207_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptitudes',
            options={'verbose_name': 'una Aptitud', 'verbose_name_plural': 'Aptitudes'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'un empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'un insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'un tipo de documento', 'verbose_name_plural': 'tipos de documentos'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'una Ubicacion', 'verbose_name_plural': 'ubicaciones'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('Elije una opci\xf3n', 'Elije una opci\xf3n'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], default='Elije una opci\xf3n', max_length=30, null=True),
        ),
    ]
