# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0002_auto_20181209_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
