# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0003_auto_20181209_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'una actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AddField(
            model_name='actividad',
            name='cantidad_insumo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre_actividad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema'),
        ),
    ]
