# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaMonitoreo', '0004_auto_20181229_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
    ]
